### ISSUE TITLE
Minor error in documentation

### ISSUE THREAD

**Issue by sn248** [InsightRX/clinPK#1]
Thank you Ron for the fantastic package. Just a small error in documentation - all the pk_2cmt_*.R still say 1-compartment model in the first line of documentation. Minor error, but it was confusing at first.

Thanks!
Satya

**Comment by jasmineirx** [comment]
Thanks @sn248! Closing this issue now that documentation has been updated in https://github.com/InsightRX/clinPK/pull/9
